parameters:
#    mmo_experiment.example.class: Mmo\Bundle\ExperimentBundle\Example

services:
#    mmo_experiment.example:
#        class: %mmo_experiment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
